"""Terminal-based ASCII visualizer integrated with MazeGenerator."""

import os
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from mazegen.generator import MazeGenerator

Coordinate = tuple[int, int]


def hex_to_ansi(hex_str: str) -> str:
    """Hex renk kodunu (#RRGGBB) ANSI TrueColor koduna dönüştürür."""
    hex_str = hex_str.lstrip("#")
    r, g, b = (int(hex_str[i:i+2], 16) for i in (0, 2, 4))
    return f"\033[38;2;{r};{g};{b}m"


class Colors:
    """ANSI Escape Codes for 24-bit TrueColor rendering."""

    RESET = "\033[0m"
    BOLD = "\033[1m"

    PALETTES = [
        hex_to_ansi("#00FF87"),
        hex_to_ansi("#00B4FF"),
        hex_to_ansi("#FF7800"),
        hex_to_ansi("#DCDCDC"),
    ]

    PATH = hex_to_ansi("#FFD700")
    START = hex_to_ansi("#FF007F")
    END = hex_to_ansi("#00D4FF")
    PATTERN = hex_to_ansi("#969696")


class MazeVisualizer:
    """Renders the maze generated by MazeGenerator into ASCII format."""

    def __init__(self, generator: "MazeGenerator") -> None:
        self.generator = generator
        self.show_path = False
        self.palette_index = 0
        self.solution_path: list[Coordinate] = []

    def _clear_screen(self) -> None:
        """Clears the terminal screen."""
        os.system("cls" if os.name == "nt" else "clear")

    def toggle_path(self) -> None:
        """Fetch solution if not loaded and toggle path visibility."""
        if not self.solution_path and self.generator.maze is not None:
            self.solution_path = self.generator.shortest_path()
        self.show_path = not self.show_path

    def rotate_colors(self) -> None:
        """Switch to next wall color palette."""
        self.palette_index = (self.palette_index + 1) % len(Colors.PALETTES)

    def render(self) -> None:
        """Draw the maze, UI controls, and any diagnostic messages."""
        maze = self.generator.maze
        if maze is None:
            print("Maze has not been generated yet!")
            return

        self._clear_screen()
        wall_color = Colors.PALETTES[self.palette_index]
        path_set = set(self.solution_path) if self.show_path else set()

        lines: list[str] = []

        for y in range(maze.height):
            top_line = ""
            mid_line = ""

            for x in range(maze.width):
                cell_walls = maze.walls[y][x]
                cell_coord = (x, y)

                # Üst Duvar (Kuzey / Bit 4)
                if cell_walls & 1:
                    top_line += f"{wall_color}+---{Colors.RESET}"
                else:
                    top_line += f"{wall_color}+   {Colors.RESET}"

                # Sol Duvar (Batı / Bit 8)
                west_wall = (
                    f"{wall_color}|{Colors.RESET}"
                    if (cell_walls & 8) else " "
                )

                # Cell içi
                if cell_coord in maze.blocked:
                    # "42" Deseni olanlar için
                    content = f"{Colors.PATTERN}███{Colors.RESET}"
                elif cell_coord == maze.entry:
                    content = f"{Colors.START}{Colors.BOLD} E {Colors.RESET}"
                elif cell_coord == maze.exit:
                    content = f"{Colors.END}{Colors.BOLD} X {Colors.RESET}"
                elif cell_coord in path_set:
                    content = f"{Colors.PATH} • {Colors.RESET}"
                else:
                    content = "   "

                mid_line += f"{west_wall}{content}"

            # En Sağ Duvar (Doğu / Bit 2)
            top_line += f"{wall_color}+{Colors.RESET}"
            east_wall = (
                f"{wall_color}|{Colors.RESET}"
                if (maze.walls[y][maze.width - 1] & 2)
                # BURAYA GEREK VAR MI EMİN DEĞİLİM!
                else " "
            )
            mid_line += east_wall

            lines.append(top_line)
            lines.append(mid_line)

        # En Alt Duvar (Güney / Bit 2)
        bottom_line = ""
        for x in range(maze.width):
            if maze.walls[maze.height - 1][x] & 4:
                bottom_line += f"{wall_color}+---{Colors.RESET}"
            else:
                # BURAYA GEREK VAR MI EMİN DEĞİLİM!
                bottom_line += f"{wall_color}+   {Colors.RESET}"
        bottom_line += f"{wall_color}+{Colors.RESET}"
        lines.append(bottom_line)

        print("\n".join(lines))

        # Hata varsa onu yazdırıyor
        if self.generator.diagnostics:
            print(f"\n{Colors.BOLD}[Diagnostics]:{Colors.RESET}")
            for diag in self.generator.diagnostics:
                print(f"  - {diag}")

        self._print_menu()

    def _print_menu(self) -> None:
        """Prints user menu controls."""
        status = "ON" if self.show_path else "OFF"
        print(f"\n{Colors.BOLD}=== A-Maze-ing Visualizer ==={Colors.RESET}")
        print("1. Re-generate a new maze")
        print(f"2. Show/Hide shortest path [{status}]")
        print("3. Rotate wall colors")
        print("4. Quit")
