"""Terminal-based ASCII visualizer integrated with MazeGenerator."""

import os
import secrets
import sys
from pathlib import Path
from typing import TYPE_CHECKING

from mazegen.output import write_output

if TYPE_CHECKING:
    from mazegen.generator import MazeGenerator

Coordinate = tuple[int, int]


def hex_to_ansi(hex_str: str) -> str:
    """Hex renk kodunu (#RRGGBB) ANSI TrueColor koduna dönüştürür."""
    hex_str = hex_str.lstrip("#")
    r, g, b = (int(hex_str[i:i+2], 16) for i in (0, 2, 4))
    return f"\033[38;2;{r};{g};{b}m"


class Colors:
    """ANSI Escape Codes for 24-bit TrueColor rendering."""

    RESET = "\033[0m"
    BOLD = "\033[1m"

    PALETTES = [
        hex_to_ansi("#00FF87"),
        hex_to_ansi("#00B4FF"),
        hex_to_ansi("#FF7800"),
        hex_to_ansi("#DCDCDC"),
    ]

    PATH = hex_to_ansi("#FFD700")
    START = hex_to_ansi("#FF007F")
    END = hex_to_ansi("#00D4FF")
    PATTERN = hex_to_ansi("#969696")


class MazeVisualizer:
    """Renders the maze generated by MazeGenerator into ASCII format."""

    def __init__(
        self,
        generator: "MazeGenerator",
        output_file: str | Path = "output_maze.txt",
    ) -> None:
        self.generator = generator
        self.output_file = output_file
        self.show_path = False
        self.palette_index = 0
        self.solution_path: list[Coordinate] = []

    def _clear_screen(self) -> None:
        """Clears the terminal screen."""
        if sys.stdout.isatty() and (os.name == "nt" or os.getenv("TERM")):
            print("\033[2J\033[H", end="")

    def regenerate(self) -> None:
        """Generate a fresh maze, save it, and reset the path overlay."""
        self.generator.seed = secrets.randbits(64)
        maze = self.generator.generate()
        write_output(maze, self.output_file)
        self.solution_path.clear()
        self.show_path = False

    def toggle_path(self) -> None:
        """Fetch solution if not loaded and toggle path visibility."""
        if not self.solution_path and self.generator.maze is not None:
            self.solution_path = self.generator.shortest_path()
        self.show_path = not self.show_path

    def rotate_colors(self) -> None:
        """Switch to next wall color palette."""
        self._clear_screen()
        self.palette_index = (self.palette_index + 1) % len(Colors.PALETTES)

    def render(self) -> None:
        """Draw the maze, UI controls, and any diagnostic messages."""
        maze = self.generator.maze
        if maze is None:
            print("Maze has not been generated yet!")
            return

        self._clear_screen()
        wall_color = Colors.PALETTES[self.palette_index]
        path_set = set(self.solution_path) if self.show_path else set()

        lines: list[str] = []

        for y in range(maze.height):
            top_line = ""
            mid_line = ""

            for x in range(maze.width):
                cell_walls = maze.walls[y][x]
                cell_coord = (x, y)

                # Top wall (North / bit 0).
                if cell_walls & 1:
                    top_line += f"{wall_color}+---{Colors.RESET}"
                else:
                    top_line += f"{wall_color}+   {Colors.RESET}"

                # Left wall (West / bit 3).
                west_wall = (
                    f"{wall_color}|{Colors.RESET}"
                    if (cell_walls & 8) else " "
                )

                # Cell content.
                if cell_coord in maze.blocked:
                    # Fully closed cells form the "42" pattern.
                    content = f"{Colors.PATTERN}███{Colors.RESET}"
                elif cell_coord == maze.entry:
                    content = f"{Colors.START}{Colors.BOLD} E {Colors.RESET}"
                elif cell_coord == maze.exit:
                    content = f"{Colors.END}{Colors.BOLD} X {Colors.RESET}"
                elif cell_coord in path_set:
                    content = f"{Colors.PATH} • {Colors.RESET}"
                else:
                    content = "   "

                mid_line += f"{west_wall}{content}"

            # Right wall (East / bit 1).
            top_line += f"{wall_color}+{Colors.RESET}"
            east_wall = (
                f"{wall_color}|{Colors.RESET}"
                if (maze.walls[y][maze.width - 1] & 2)
                else " "
            )
            mid_line += east_wall

            lines.append(top_line)
            lines.append(mid_line)

        # Bottom wall (South / bit 2).
        bottom_line = ""
        for x in range(maze.width):
            if maze.walls[maze.height - 1][x] & 4:
                bottom_line += f"{wall_color}+---{Colors.RESET}"
            else:
                bottom_line += f"{wall_color}+   {Colors.RESET}"
        bottom_line += f"{wall_color}+{Colors.RESET}"
        lines.append(bottom_line)

        print("\n".join(lines))

        # Explain non-fatal choices such as omitting an oversized pattern.
        if self.generator.diagnostics:
            print(f"\n{Colors.BOLD}[Diagnostics]:{Colors.RESET}")
            for diag in self.generator.diagnostics:
                print(f"  - {diag}")

        self._print_menu()

    def _print_menu(self) -> None:
        """Prints user menu controls."""
        status = "ON" if self.show_path else "OFF"
        print(f"\n{Colors.BOLD}=== A-Maze-ing Visualizer ==={Colors.RESET}")
        print("1. Re-generate a new maze")
        print(f"2. Show/Hide shortest path [{status}]")
        print("3. Rotate wall colors")
        print("4. Quit")

    def run(self) -> None:
        """Render the maze and process terminal commands until quit."""
        while True:
            self.render()
            try:
                choice = input("Choose an option [1-4]: ").strip()
            except (EOFError, KeyboardInterrupt):
                print("\nExiting visualizer.")
                return
            if choice == "1":
                self.regenerate()
            elif choice == "2":
                self.toggle_path()
            elif choice == "3":
                self.rotate_colors()
            elif choice == "4":
                print("Exiting visualizer.")
                return
            else:
                print("Invalid option. Enter a number from 1 to 4.")
